create table if not exists public.inventory_delivery_history (
  id bigint generated by default as identity primary key,
  "accountId" bigint not null references public.accounts(id) on delete cascade,
  "transactionId" bigint not null references public.transactions(id) on delete cascade,
  "transactionDetailId" bigint not null references public."transactionDetails"(id) on delete cascade,
  "conceptId" bigint references public.concepts(id) on delete set null,
  "deliveryBatchKey" text not null,
  "deliveryDate" date not null default current_date,
  quantity numeric not null check (quantity > 0),
  "createdAt" timestamptz not null default timezone('utc', now())
);

create index if not exists inventory_delivery_history_account_idx
  on public.inventory_delivery_history ("accountId");

create index if not exists inventory_delivery_history_transaction_idx
  on public.inventory_delivery_history ("transactionId");

create index if not exists inventory_delivery_history_batch_idx
  on public.inventory_delivery_history ("deliveryBatchKey");

alter table public.inventory_delivery_history enable row level security;

drop policy if exists "inventory_delivery_history_tenant_access" on public.inventory_delivery_history;
create policy "inventory_delivery_history_tenant_access"
on public.inventory_delivery_history
for all
to authenticated
using (public.user_belongs_to_account("accountId"))
with check (public.user_belongs_to_account("accountId"));
