import { PGlite } from "npm:@electric-sql/pglite@0.3.14";
import assert from "node:assert/strict";

Deno.test("budget migration validates accounts and preserves invoice income snapshots", async () => {
  const db = new PGlite();
  const query = (sql: string) => db.query<Record<string, unknown>>(sql);
  try {
    await db.exec(`
      create role authenticated;
      create table concepts(id bigint primary key, "accountId" bigint, name text,
        "isIncome" boolean default false, "isExpense" boolean default false,
        "isGroup" boolean default false, "isProduct" boolean default false, "isSystem" boolean default false);
      create table budgets(id bigint primary key, "accountId" bigint);
      create table budget_lines(id bigint generated by default as identity (start with 100) primary key, "budgetId" bigint references budgets,
        "conceptId" bigint references concepts, amount double precision, "createdById" uuid,
        constraint budget_lines_budget_concept_unique unique ("budgetId","conceptId"));
      create table transactions(id bigint primary key, "accountId" bigint, type integer,
        tags text[] default '{}', "sourceTransactionId" bigint);
      create table "transactionDetails"(id bigint primary key, "transactionId" bigint references transactions,
        "conceptId" bigint references concepts, "transactionPaidId" bigint,
        quantity double precision, net double precision, discount double precision, "additionalCharges" double precision);
      insert into concepts(id,"accountId",name,"isIncome") values (10,8,'Services',true),(11,8,'Other income',true),(12,9,'Foreign',true);
      insert into concepts(id,"accountId",name,"isProduct","isIncome") values (20,8,'Product',true,true);
      insert into concepts(id,"accountId",name,"isExpense") values (30,8,'Expense',true);
      insert into budgets values (1,8);
      insert into budget_lines(id,"budgetId","conceptId",amount) values (1,1,30,200);
      insert into transactions(id,"accountId",type) values (1,8,1),(2,8,1),(3,9,1);
      insert into "transactionDetails"(id,"transactionId","conceptId",quantity,net) values (1,1,20,1,50);
    `);
    await db.exec(await Deno.readTextFile("supabase/migrations/20260924052625_budget_income_expense_execution.sql"));
    assert.equal((await query('select "lineType" from budget_lines')).rows[0].lineType, "expense");
    assert.equal((await query('select "incomeAllocation" from "transactionDetails" where id=1')).rows[0].incomeAllocation, null);
    await assert.rejects(db.exec('update concepts set "incomeConceptId"=12 where id=20'), /Invalid income/);
    await assert.rejects(db.exec('update concepts set "incomeConceptId"=30 where id=20'), /Invalid income/);
    await assert.rejects(db.exec(`insert into budget_lines(id,"budgetId","conceptId",amount,"lineType") values(2,1,12,100,'income')`), /Invalid budget/);
    await assert.rejects(db.exec(`insert into budget_lines(id,"budgetId","conceptId",amount,"lineType") values(2,1,30,100,'income')`), /Invalid budget/);
    await assert.rejects(db.exec(`select replace_budget_lines(1,8,'[{"conceptId":12,"lineType":"income","amount":1}]')`), /Invalid budget/);
    assert.equal((await query('select amount from budget_lines where id=1')).rows[0].amount, 200);
    await db.exec(`select replace_budget_lines(1,8,'[{"conceptId":10,"lineType":"income","amount":100},{"conceptId":30,"lineType":"expense","amount":40}]')`);
    assert.equal((await query('select * from budget_lines')).rows.length, 2);
    await assert.rejects(db.exec(`select replace_budget_lines(1,9,'[{"conceptId":10,"lineType":"income","amount":1}]')`), /not found/);
    await assert.rejects(db.exec(`select replace_budget_lines(1,8,null)`), /required/);
    await db.exec(`update concepts set "incomeConceptId"=10 where id=20;
      insert into "transactionDetails"(id,"transactionId","conceptId",quantity,net,discount,"additionalCharges") values (2,2,20,2,200,20,5);`);
    const allocation = { conceptId: 10, name: "Services" };
    assert.deepEqual((await query('select "incomeAllocation" from "transactionDetails" where id=2')).rows[0].incomeAllocation, allocation);
    await db.exec(`update concepts set "incomeConceptId"=11 where id=20;
      update "transactionDetails" set net=220 where id=2;`);
    assert.deepEqual((await query('select "incomeAllocation" from "transactionDetails" where id=2')).rows[0].incomeAllocation, allocation);
    // The editor carries the original JSON through its delete/reinsert path.
    await db.exec(`delete from "transactionDetails" where id=2;
      insert into "transactionDetails"(id,"transactionId","conceptId",quantity,net,discount,"additionalCharges","incomeAllocation")
      values (2,2,20,2,200,20,5,'{"conceptId":10,"name":"Services"}');
      delete from "transactionDetails" where id=1;
      insert into "transactionDetails"(id,"transactionId","conceptId",quantity,net,"incomeAllocation") values (1,1,20,1,50,'{}');`);
    assert.deepEqual((await query('select "incomeAllocation" from "transactionDetails" where id=1')).rows[0].incomeAllocation, {});
    await assert.rejects(db.exec(`insert into "transactionDetails"(id,"transactionId","conceptId") values(3,3,20)`), /account/);
    await db.exec(`insert into transactions values (4,8,2,'{__sale_return__,__inventory_adjustment__}',2);
      insert into "transactionDetails"(id,"transactionId","conceptId","transactionPaidId",quantity) values(4,4,20,2,1);`);
    const returned = (await query('select "incomeAllocation", "budgetIncomeReversal" from "transactionDetails" where id=4')).rows[0];
    assert.deepEqual(returned.incomeAllocation, allocation);
    assert.equal(Number(returned.budgetIncomeReversal), 92.5);
  } finally {
    await db.close();
  }
});
